export type BlogSection = { id: string; title: string; paragraphs: string[]; points?: string[] };
export type BlogArticle = {
  slug: string; title: string; summary: string; excerpt: string; category: string; author: string;
  published: string; updated: string; readingTime: string; relatedService: { label: string; href: `/${string}` };
  sections: BlogSection[]; relatedSlugs: string[]; isPublished: boolean;
};

const common = { author: "BoomoTech Team", published: "2026-09-24", updated: "2026-09-24", isPublished: true } as const;

export const blogArticles: BlogArticle[] = [
  {
    ...common, slug: "essential-it-support-checklist-small-business", category: "IT support", readingTime: "7 min read",
    title: "Essential IT Support Checklist for Small Businesses",
    summary: "A practical checklist for keeping devices, accounts, backups, email and everyday technology dependable.",
    excerpt: "Use this checklist to review the technology foundations that support daily work and identify gaps before they become interruptions.",
    relatedService: { label: "Explore IT support", href: "/services/it-support" }, relatedSlugs: ["improve-small-business-wifi-network", "practical-cybersecurity-steps-australian-small-businesses"],
    sections: [
      { id: "devices", title: "Set up and maintain every device", paragraphs: ["Keep an accurate list of business computers, phones and shared devices. Record who uses each device, its operating system and its warranty or replacement status.", "Apply operating system, browser and application updates promptly. Automatic updates help, but someone should still check that devices restart and complete them."], points: ["Remove software that is no longer needed", "Encrypt portable devices where supported", "Plan replacements before hardware becomes unreliable"] },
      { id: "accounts", title: "Give each person the right access", paragraphs: ["Use individual accounts so activity and access can be managed properly. Shared administrator accounts make changes difficult to trace and harder to revoke when someone leaves.", "Document how accounts are created, changed and disabled. Review access when roles change, not only during onboarding and offboarding."], points: ["Turn on multi-factor authentication", "Keep administrator access separate from everyday work", "Remove dormant accounts"] },
      { id: "backups", title: "Make backups ready for recovery", paragraphs: ["Know which files, mailboxes and systems are backed up, where the copies are stored and who is responsible for checking them. File synchronisation alone may not provide the recovery history the business needs.", "Test a small restore on a regular schedule. A successful backup notification is useful, but a restore test shows whether people can recover usable information."], points: ["Keep an independent copy of important data", "Protect backup administration with strong access controls", "Write down the restore process"] },
      { id: "security", title: "Cover endpoint and email basics", paragraphs: ["Use supported security software, device firewalls and automatic screen locking. Microsoft 365 and other email platforms also need deliberate account, sharing and recovery settings.", "Teach staff to pause before opening unexpected attachments, following sign-in links or approving MFA prompts they did not initiate."], points: ["Review mailbox forwarding rules", "Confirm recovery details belong to the business", "Report suspicious messages through a known channel"] },
      { id: "network", title: "Check Wi-Fi and network reliability", paragraphs: ["Place network equipment where it can provide useful coverage and keep its firmware current. Separate guest access from business devices and replace default administration passwords.", "Document the internet provider, router, access points and important cabling. This shortens diagnosis when a connection fails."], points: ["Test coverage where people actually work", "Label network equipment and cables", "Keep configuration backups where appropriate"] },
      { id: "documentation", title: "Write down what matters", paragraphs: ["Useful documentation includes suppliers, account ownership, device details, backup responsibilities and the first steps for common incidents. Store it somewhere protected that authorised people can reach during an outage.", "Contact professional IT support when recurring faults interrupt work, access or ownership is unclear, a security incident is suspected, or a change could affect important systems. BoomoTech can help clarify the issue and plan a safe next step."], points: ["Review the checklist after significant staff or system changes", "Use the consultation request to describe the current environment and priority"] },
    ],
  },
  {
    ...common, slug: "improve-small-business-wifi-network", category: "Networks", readingTime: "6 min read",
    title: "How to Improve Your Small Business Wi-Fi and Network",
    summary: "Practical ways to improve coverage, reliability and security before buying more network equipment.",
    excerpt: "Start with placement, interference, cabling and secure configuration to find the real cause of unreliable workplace Wi-Fi.",
    relatedService: { label: "Explore Network and Wi-Fi", href: "/services/network-wifi" }, relatedSlugs: ["essential-it-support-checklist-small-business", "practical-cybersecurity-steps-australian-small-businesses"],
    sections: [
      { id: "placement", title: "Start with router and access-point placement", paragraphs: ["Wi-Fi performs best when access points are close to the people and devices using them, with fewer dense walls, metal cabinets and electrical sources in the way. A router hidden at one end of a workplace may never cover the whole space reliably.", "Move equipment only after noting the current setup. Test in meeting rooms, work areas and other places where calls or cloud applications matter."], points: ["Keep access points elevated and unobstructed", "Use wired links between access points where practical", "Measure at busy times as well as quiet ones"] },
      { id: "equipment", title: "Choose equipment for business use", paragraphs: ["Business-grade equipment can provide better management, security updates and support for multiple access points. The right choice still depends on layout, device count, internet connection and the features the team will actually maintain.", "Adding another consumer extender can sometimes add interference or create confusing roaming behaviour. Diagnose the constraint before buying hardware."] },
      { id: "guest-network", title: "Separate guests and important systems", paragraphs: ["Provide a guest network for visitors and personal devices. Keep it isolated from business computers, file storage and network administration.", "For environments with point-of-sale, cameras or connected equipment, network segmentation can reduce unnecessary access between device groups. Configuration should remain documented and supportable."], points: ["Use unique, strong administration credentials", "Limit management access", "Review who knows shared Wi-Fi passwords"] },
      { id: "maintenance", title: "Keep firmware and configuration current", paragraphs: ["Install vendor firmware updates and replace equipment that no longer receives security support. Save a protected configuration backup before material changes.", "Use modern Wi-Fi security settings supported by the devices. Avoid publishing administration interfaces to the internet unless a carefully managed requirement exists."] },
      { id: "slow", title: "Find common causes of slow or unreliable Wi-Fi", paragraphs: ["Congested channels, poor placement, interference, weak cabling, an overloaded router and a slow internet service can look similar to users. Test the wired internet connection and local Wi-Fi separately so the correct problem is addressed.", "A professional network assessment is useful when coverage problems persist, a move or fit-out is planned, important systems need separation, or nobody can explain the existing design. BoomoTech can review the symptoms and recommend practical next steps."], points: ["Record when and where problems occur", "Note which devices are affected", "Avoid factory resets before saving required settings"] },
    ],
  },
  {
    ...common, slug: "practical-cybersecurity-steps-australian-small-businesses", category: "Cybersecurity", readingTime: "8 min read",
    title: "Practical Cybersecurity Steps for Australian Small Businesses",
    summary: "Straightforward security practices for accounts, devices, backups and incident preparation.",
    excerpt: "Strengthen everyday security with multi-factor authentication, safer account access, tested backups and a simple response plan.",
    relatedService: { label: "Explore Cybersecurity", href: "/services/cybersecurity" }, relatedSlugs: ["essential-it-support-checklist-small-business", "improve-small-business-wifi-network"],
    sections: [
      { id: "mfa", title: "Use multi-factor authentication", paragraphs: ["Enable multi-factor authentication for email, banking, cloud administration and other important services. Prefer authenticator apps or security keys where they are available and suitable.", "Unexpected approval prompts can indicate that someone already has a password. Teach users to deny prompts they did not initiate and report them through a known contact path."], points: ["Protect recovery accounts too", "Keep recovery codes in a restricted location", "Review older authentication methods"] },
      { id: "passwords", title: "Adopt a password manager", paragraphs: ["A reputable password manager helps people create a unique password for every service without relying on predictable variations. Protect the password manager with a strong master password and MFA.", "Do not send passwords, MFA codes or recovery keys through booking, contact or support messages. A legitimate support process should use safer ways to arrange access."] },
      { id: "updates", title: "Keep software and devices supported", paragraphs: ["Apply security updates to operating systems, browsers, applications, routers and connected devices. Remove obsolete applications and plan to replace systems that no longer receive vendor updates.", "Limit administrator rights for routine work. Separate administrative accounts reduce the effect of a malicious download or accidental change."], points: ["Maintain a device inventory", "Turn on automatic updates where appropriate", "Check that restarts complete updates"] },
      { id: "phishing", title: "Prepare people for phishing", paragraphs: ["Encourage staff to verify unusual payment, password reset and document-sharing requests using a trusted second channel. Attackers often create urgency or imitate a familiar sender.", "Make reporting simple and blame-free. Early reports give the business more time to reset access, check mailbox rules and contact affected parties."] },
      { id: "backups", title: "Keep tested, protected backups", paragraphs: ["Back up important business information according to its value and rate of change. Keep at least one copy that is not continuously exposed to the same accounts and devices as the original.", "Test restores and record the steps. Include key cloud data rather than assuming every platform can recover deleted or encrypted information indefinitely."] },
      { id: "response", title: "Create a small incident-response plan", paragraphs: ["Write down who will make decisions, how staff will communicate if email is unavailable, which providers to contact and how evidence will be preserved. Keep an accessible copy away from the systems it covers.", "Request a security review when access ownership is unclear, MFA or backups are inconsistent, a suspicious event has occurred, or important systems are changing. A review can prioritise practical improvements, but no security measure can guarantee that an incident will never occur."], points: ["Avoid making unverified legal or regulatory assumptions", "Confirm notification obligations with qualified advisers", "Review the plan after changes and exercises"] },
    ],
  },
];

export const publishedArticles = blogArticles.filter((article) => article.isPublished);
export const articleBySlug = new Map(blogArticles.map((article) => [article.slug, article]));
