import type { SolutionRecord } from "./types";

const solution = (record: Omit<SolutionRecord, "kind" | "eyebrow" | "publication" | "indexable">): SolutionRecord => ({
  ...record,
  kind: "solution",
  eyebrow: "Who we help",
  publication: "published",
  indexable: true,
});

export const solutions: SolutionRecord[] = [
  solution({ path: "/solutions/small-business", title: "Technology that supports a growing business", description: "Bring day-to-day support, safer foundations and practical improvement into one clearer plan.", metaDescription: "Practical technology solutions for Brisbane and Australian small businesses without a dedicated IT team.", audience: "Owners and growing teams balancing customer work with technology decisions, often without a dedicated IT function.", challenges: [{ title: "Daily interruptions", description: "Recurring device, account and network issues make focused work harder." }, { title: "Unclear ownership", description: "Nobody is sure who maintains systems, access, backups or supplier relationships." }, { title: "Growth friction", description: "Onboarding, collaboration and administration have not kept pace with the team." }], priorities: ["Stabilise the issues affecting work now", "Clarify access, backup and security foundations", "Document ownership and repeatable routines", "Create a realistic improvement roadmap"], approach: [{ number: "01", title: "Start with impact", description: "Identify what is interrupting work or creating avoidable risk." }, { number: "02", title: "Set practical priorities", description: "Separate urgent fixes from improvements that can be staged." }, { number: "03", title: "Build a workable plan", description: "Connect support, systems and future projects without unnecessary complexity." }], related: [{ label: "Managed IT", href: "/services/managed-it" }, { label: "Cybersecurity foundations", href: "/services/cybersecurity" }, { label: "Book a consultation", href: "/book/consultation" }] }),
  solution({ path: "/solutions/professional-services", title: "Reliable systems for focused professional work", description: "Support secure collaboration, client work and repeatable administration with clearer technology choices.", metaDescription: "Technology planning for Australian professional services teams seeking reliable collaboration and safer workflows.", audience: "Professional teams that depend on email, documents, meetings and client information to deliver consistent work.", challenges: [{ title: "Scattered information", description: "Files, conversations and tasks are spread across tools without a clear structure." }, { title: "Access changes", description: "Joiners, leavers and external collaborators create recurring access questions." }, { title: "Manual administration", description: "Routine work consumes time and is difficult to audit or hand over." }], priorities: ["Make collaboration easier to understand", "Strengthen identity and access routines", "Map privacy-sensitive workflows before changing tools", "Automate carefully with human review"], approach: [{ number: "01", title: "Map the work", description: "Understand how information moves through the team." }, { number: "02", title: "Reduce friction", description: "Improve the highest-impact systems and hand-offs first." }, { number: "03", title: "Keep control visible", description: "Document access, review and escalation responsibilities." }], related: [{ label: "Microsoft 365", href: "/services/microsoft-365" }, { label: "AI and automation", href: "/services/ai-automation" }, { label: "Cybersecurity foundations", href: "/services/cybersecurity" }] }),
  solution({ path: "/solutions/retail", title: "Connected technology for retail work", description: "Clarify the devices, connectivity and digital touchpoints that support staff and customers.", metaDescription: "Practical technology planning for retail businesses, covering connectivity, devices, access and digital presence.", audience: "Retail operators reviewing store connectivity, staff devices, digital presence or the systems behind daily service.", challenges: [{ title: "Connectivity gaps", description: "Coverage or reliability issues interrupt devices and staff workflows." }, { title: "Shared access", description: "Accounts and devices are shared without clear responsibility or handover." }, { title: "Disconnected channels", description: "Customer information and online touchpoints do not align with the real store experience." }], priorities: ["Understand critical store dependencies", "Improve network and device reliability", "Clarify staff access and support paths", "Keep customer-facing information consistent"], approach: [{ number: "01", title: "Identify essentials", description: "Map what must work for staff and customers." }, { number: "02", title: "Plan resilience", description: "Address avoidable single points of failure and unclear ownership." }, { number: "03", title: "Connect the experience", description: "Align digital touchpoints with practical store operations." }], related: [{ label: "Network and Wi-Fi", href: "/services/network-wifi" }, { label: "Digital presence", href: "/services/digital-presence" }, { label: "IT support", href: "/services/it-support" }] }),
  solution({ path: "/solutions/home-office-individuals", title: "Clear technology help at home", description: "Make devices, accounts, Wi-Fi and backups easier to understand and safer to use.", metaDescription: "Practical technology support guidance for Brisbane home offices and individuals, with remote options where suitable.", audience: "Individuals and home-office workers who want clear help without jargon, pressure or unsafe credential sharing.", challenges: [{ title: "Unreliable setup", description: "Wi-Fi, printers, calls or devices do not work consistently together." }, { title: "Account confusion", description: "Email, storage and recovery options are difficult to understand." }, { title: "Replacement decisions", description: "It is unclear whether to repair, replace or reconfigure equipment." }], priorities: ["Resolve the issue affecting work or daily use", "Protect important accounts and files", "Make the setup easier to maintain", "Explain purchasing choices before spending"], approach: [{ number: "01", title: "Describe the problem", description: "Start with what you see and when it happens." }, { number: "02", title: "Choose a safe path", description: "Decide whether remote guidance or onsite assessment is appropriate." }, { number: "03", title: "Leave with clarity", description: "Understand what changed and what to do next." }], related: [{ label: "IT support", href: "/services/it-support" }, { label: "Network and Wi-Fi", href: "/services/network-wifi" }, { label: "Support safety", href: "/support/safety" }] }),
  solution({ path: "/solutions/remote-work", title: "Remote work without the avoidable friction", description: "Connect people, access and collaboration practices across locations.", metaDescription: "Remote work technology planning for Australian teams, covering access, collaboration, devices and support.", audience: "Teams working across offices, homes or client sites that need consistent access and support practices.", challenges: [{ title: "Inconsistent access", description: "People use different methods to reach files, systems and shared information." }, { title: "Support at a distance", description: "Remote issues are difficult to describe, triage and resolve safely." }, { title: "Collaboration overload", description: "Messages, meetings and documents spread across too many places." }], priorities: ["Define secure access patterns", "Standardise essential device and account setup", "Make support and escalation easy to follow", "Reduce tool overlap where practical"], approach: [{ number: "01", title: "Understand locations", description: "Map where people work and which systems they need." }, { number: "02", title: "Set shared patterns", description: "Create repeatable access, collaboration and support routines." }, { number: "03", title: "Test real scenarios", description: "Check that the approach works in normal and disrupted conditions." }], related: [{ label: "Microsoft 365", href: "/services/microsoft-365" }, { label: "Remote support", href: "/support/remote" }, { label: "Cloud and infrastructure", href: "/services/cloud-infrastructure" }] }),
];

export const solutionByPath = new Map(solutions.map((item) => [item.path, item]));
